server:
  port: 8000

spring:
  application:
    name: BE_FoodOrder_Platform

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_FoodOrder_Platform;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 12345

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update